Laboratory work #1, Irina Sozinova
fss-python/2022-basic-labs pull request #10
Opened 2022-03-03 13:29 UTC by IrinaSozinova

2022-03-16 20:30 UTC, AlexeyChikhachev commented on lab_1/main.py
> +    threshold=float(max(signal))*0.8
Результат умножения вещественного(float) числа на любое число так же является вещественным числом, потому приведение к float в данном случае можно опустить. Это немного упростит чтение кода и его поддержку.

2022-03-16 20:30 UTC, AlexeyChikhachev commented on lab_1/main.py
>      return threshold
Поскольку с переменной threshold никаких действий не выполняется, можно сразу вернуть значение выражения и сократить размер функции на пару строчек.

2022-03-16 20:32 UTC, AlexeyChikhachev commented on lab_1/main.py
>  def calculate_threshold(signal: list):
Нужно обратить внимание на правильность входных данных. По условиям задачи функция должна возвращать None, если входной список signal содержит неправильные значения или не содержит никаких значений.
Такую проверку обязательно нужно делать, даже когда мы ожидаем, что данные будут правильными.В случае, если данных много, отсутствие таких проверок может привести к направильным результатам и саму эту "неправильность", как и ее причину, не всегда просто обнаружить.

2022-03-16 20:35 UTC, AlexeyChikhachev commented on lab_1/main.py
>      ecg_times.append(0)
Почти правильно. При таком подходе у размер ecg_times будет на 1 больше чем размер signal. Значения ecg_times можно сразу посчитать oт i: шаг у нас действительно фиксированный 1000/sample_rate, а колчичество шагов на каждой итерации равно i.

2022-03-16 20:36 UTC, AlexeyChikhachev commented on lab_1/main.py
>      """Calculating timestamp for each item in ECG"""
Не забываем про проверку входных данных. По условиям задачи функция должна возвращать None, если на входе некорректные значения.

2022-03-16 20:37 UTC, AlexeyChikhachev commented on lab_1/main.py
>      """Extract RR intervals"""
Не забываем про проверку входных данных. По условиям задачи функция должна возвращать None, если на входе некорректные значения. :)

2022-03-16 20:40 UTC, AlexeyChikhachev commented on lab_1/main.py
>      for i in range(len(rr_without_threshold)):
Эту конструкцию можно немного упростить, заменив ее на на "for rr in rr_without_threshold", т.е. берем каждое значение в rr_without_threshold, а в цикле использовать просто rr, вместо rr_without_threshold[i]

2022-03-16 20:41 UTC, AlexeyChikhachev commented on lab_1/main.py
>          else:
Ветка else опциональная - если в ней ничего не происходит, то можно ее опустить.

2022-03-16 21:16 UTC, AlexeyChikhachev commented on lab_1/main.py
> +    high_markers_ms=[0.0]
Тут небольшая неточность: high_markers_ms[0]  = 0.0, значит, что в начале ЭКГ всегда пик, независимо от того, есть ли он в данных или нет, а если следующий пик в данных через 400мс, то получится неверный рр-интервал.

2022-03-16 21:54 UTC, AlexeyChikhachev commented on lab_1/main.py
>          elif signal[i+1]<signal[i] and signal[i-1]<signal[i]:
Что получится в elif, если i = 0, а signal[i] > threshold?

2022-03-17 08:54 UTC, IrinaSozinova commented on lab_1/main.py
> +    threshold=float(max(signal))*0.8
Поняла. Исправлю.

2022-03-17 08:58 UTC, IrinaSozinova commented on lab_1/main.py
>      return threshold
а в этом случае, если не обозначить переменную threshold, а сразу вернуть значение функции, откуда дальнейшие функции будут брать переменную threshold? или где-то это закодировано, что значение эна выходе этой функции записывается в переменную threshold?

2022-03-17 08:58 UTC, IrinaSozinova commented on lab_1/main.py
>      return threshold
но, комментарий поняла, исправлю, это просто вопросы на собственное понимание процессов.

2022-03-17 09:01 UTC, IrinaSozinova commented on lab_1/main.py
>      """Calculating timestamp for each item in ECG"""
то есть проверку нужно прописать в функции, верно?

2022-03-17 09:02 UTC, IrinaSozinova commented on lab_1/main.py
>  def calculate_threshold(signal: list):
то есть проверку нужно прописать в функции до выполнения всех дальнейших операций?

2022-03-17 09:04 UTC, IrinaSozinova commented on lab_1/main.py
>      """Extract RR intervals"""
:)

2022-03-17 09:05 UTC, IrinaSozinova commented on lab_1/main.py
>      for i in range(len(rr_without_threshold)):
ок

2022-03-17 09:05 UTC, IrinaSozinova commented on lab_1/main.py
>          else:
ок

2022-03-17 10:58 UTC, AlexeyChikhachev commented on lab_1/main.py
>      return threshold
Фнукция вернет значение и мы его обычно куда-то сразу записываем. Например в нашей лаборатоной работы, это происходит в строчке threshold = calculate_threshold(signal=ecg_raw).

Еще важно помнить, что переменная объявленная внутри функции "живет" только внутри функции, после того, как функция закончила работу, все переменные, которые были объявлены внутри этой функции уничтожаются.
Поэтому threshold внутри функции и threshold снаружи, которому мы присваиваем значение  threshold = calculate_threshold(signal=ecg_raw это разные переменные.

Можно проиллюстрировать это так:

a = 1
print("снаружи:", a) #результат 1

def sample_func():
 # несмотря на идентичное имя, это другая переменная, которая видна только внутри функции,
 # из-за одинакового имени, мы не видим переменную, которая объявлена снаружи.
      a = 2
      print("внутри:", a) #результат 2

sample_func()
print(a) #результат 1

2022-03-17 11:00 UTC, AlexeyChikhachev commented on lab_1/main.py
>  def calculate_threshold(signal: list):
да, данные лучше проверять, перед тем как работать с ними. развернутый комментарий отправил в наш чат.

2022-03-17 11:00 UTC, AlexeyChikhachev commented on lab_1/main.py
>      """Calculating timestamp for each item in ECG"""
верно

2022-03-17 12:08 UTC, IrinaSozinova commented on lab_1/main.py
>      return threshold
поняла

2022-03-17 12:09 UTC, IrinaSozinova commented on lab_1/main.py
> +    high_markers_ms=[0.0]
поняла, исправлю

2022-03-17 12:13 UTC, IrinaSozinova commented on lab_1/main.py
>          elif signal[i+1]<signal[i] and signal[i-1]<signal[i]:
в elif должно пройти сравнение сначала первого числа в списке и нулевого, а затем сравнение последнего и нулевого? что является ошибкой для поставленной задаче. поняла, буду думать как исправить.

2022-03-17 12:48 UTC, AlexeyChikhachev commented on lab_1/main.py
>          elif signal[i+1]<signal[i] and signal[i-1]<signal[i]:
Тут момент еще чисто логический: signal[i-1], при i = 0

2022-03-17 13:47 UTC, IrinaSozinova commented on lab_1/main.py
>          elif signal[i+1]<signal[i] and signal[i-1]<signal[i]:
это получится signal [-1]? то есть последний элемент списка? или я неправильно помню

2022-03-17 15:35 UTC, AlexeyChikhachev commented on lab_1/main.py
>          elif signal[i+1]<signal[i] and signal[i-1]<signal[i]:
Все правильно. В данном случае вернется последний элемент списка. Из-за особенностей питона мы тут получили ошибку логическую. 

В общем случае, при работе с индексами элементов важно держать в голове размер списка в голове. 
При индексе -1 мы получим неожиданное значение в условии.

А вот тут signal[i+1], если i - это индекс последнего элемента в списке, мы получим ошибку, потому что мы вышли за границы размера списка.

Можно для наглядности попробовать программу из 2 строчек
a=[0,1,2] #индекс списка от 0 до 2
print(a[3]) #пытаемся обратиться к несуществующему элементу списка

2022-03-17 15:46 UTC, IrinaSozinova commented on lab_1/main.py
>          elif signal[i+1]<signal[i] and signal[i-1]<signal[i]:
поняла. спасибо!

2022-03-17 15:56 UTC, IrinaSozinova commented on lab_1/main.py
>          elif signal[i+1]<signal[i] and signal[i-1]<signal[i]:
чтобы точно понять. условие for i in range(len(signal)): позволяет избежать выхода за список в формуле elif signal[i+1]<signal[i] and signal[i-1]<signal[i]: Вроде бы не должен. Но почему тогда в пайчарме не выдает ошибки? Получается, чтобы код правильно работал, нужно брать сред от второго до предпоследнего элемента?

2022-03-17 22:58 UTC, AlexeyChikhachev commented on lab_1/main.py
>          elif signal[i+1]<signal[i] and signal[i-1]<signal[i]:
Да, тут есть место, где можно запутаться, но это с практикой быстро станет понятным. На самом деле, ошибки связанные с индексацией, очень распространены даже у очень опытных программистов.

Разложим этот код на составные части на примере (как обычно:)).
a = [1, 2, 3]
len(a) - вернет 3 - это количество элементов в листе. 
что у нас вернет range(len(a))? - 3 числа от 0 с шагом 1. т.е. 0, 1, 2 - это совпадает с индексацией элементов листа.

Цикл for i in range(len(а)) у нас выполнится 3 раза и i будет меняться от 0 до 2. Пока все верно.
Но как только в цикле мы начинаем добавлять к i какие-то значения, возникает проблема:
a = [1, 2, 3]
for i in range(len(a)):
    print(a[i + 1])
На последней итерации, когда i == 2, мы добавляем еще 1 и получаем индекс равный 3, а такого элемента нет,
поскольку у нас всего 3 элемента в листе, а индескация элементов начинается с 0. Т.е. с i все в порядке, а вот i+1 подводит :)
Такая же ситуация у нас и с signal[i+1].

Пайчарм не выдает ошибку, потому что он следит только за правильностью с точки зрения синтаксиса. А ошибка, которую мы обсуждаем - логическая, которая выявится только во время исполнения программы на конкретных значениях. Т.е. например на пустом листе ошибки не будет, т.к. мы не зайдем в цикл, а вот на любом другом может, но только при условии, что мы на последней итерации попали в elif. Такое для Пайчарма слишком сложно :)

2022-03-18 04:55 UTC, IrinaSozinova commented on lab_1/main.py
>          elif signal[i+1]<signal[i] and signal[i-1]<signal[i]:
ясно, спасибо!

2022-03-21 22:15 UTC, AlexeyChikhachev commented on lab_1/main.py
> +            else:
Почти идеально в рамках нашей лабы. Единственный момент на внимательность: else у нас сработает для первого же float значения, а return - это выход из функции. Т.е. проверка if type(i) != float в такой версии кода работает ровно 1 раз: либо при некорректном значении сразу выходим с None, либо сразу выходим с max(signal))*0.8. Нам же нужно проверить весь лист перед перед тем как считать порог. Нужна ли ветка else?

2022-03-21 22:56 UTC, AlexeyChikhachev commented on lab_1/main.py
> +                if signal[0] > threshold and signal[0] > signal[1]:
Когда мы пишем код в цикле, не забываем, что вся внутренность цикла выполняется на каждой итерации.
т.е. для каждого i мы будем выполнять 
            if type(i) != float:
                return None
            else:
                ecg_maximums = []
                if signal[0] > threshold and signal[0] > signal[1]:

Т.е. на каждой итерации мы будем добавлять лишние 0 или 1.
Уникальные условия, которые выполняются только для нескольких элементов из листа, можно вынести из цикла, чтобы они выполнялись только один раз.

2022-03-21 22:59 UTC, AlexeyChikhachev commented on lab_1/main.py
> +            for i in range(len(signal[1:])):
у range есть более удобная форма задания диапазона значений, которая тут может пригодиться:
range (стартовое значение, значения для остановки)

Т.е. range(1,3) даст результат 1,2

2022-03-21 23:01 UTC, AlexeyChikhachev commented on lab_1/main.py
> +                ecg_times.append(0.0)
Когда мы пишем код в цикле, не забываем, что вся внутренность цикла выполняется на каждой итерации.
Тут мы тоже на каждой итерации мы будем добавлять лишний 0.

2022-03-21 23:03 UTC, AlexeyChikhachev commented on lab_1/main.py
> +                    else:
Тут тот же вопрос к необходимости ветки else.

2022-03-21 23:07 UTC, AlexeyChikhachev commented on lab_1/main.py
> +                    ecg_times.append(ecg_times[i]+1000/sample_rate)
Такая подход нам даст правильный результат теперь. Отлично. Можно еще чуть проще, без предыдущего элемента. Так как мы знаем, что шаг фиксированный, то можно написать i * 1000/sample_rate

2022-03-22 07:16 UTC, AlexeyChikhachev commented on lab_1/main.py
> +            for i in range(len(signal[1:])):
Во вложенных циклах, чтобы избежать ошибок, лучше использовать разные буквы для итераций. Обычно используют i, j и k, хотя на можно использовать любые, главное, чтобы они были разные.
for i in range (...)
    for j in range (...)
         for k in range (...)

2022-03-22 14:13 UTC, IrinaSozinova commented on lab_1/main.py
> +                if signal[0] > threshold and signal[0] > signal[1]:
исправлено

2022-03-22 14:14 UTC, IrinaSozinova commented on lab_1/main.py
> +            for i in range(len(signal[1:])):
поняла. спасибо!

2022-03-22 14:14 UTC, IrinaSozinova commented on lab_1/main.py
> +                ecg_times.append(0.0)
исправлено

2022-03-22 14:14 UTC, IrinaSozinova commented on lab_1/main.py
> +                    else:
убрала

2022-03-22 14:15 UTC, IrinaSozinova commented on lab_1/main.py
> +                    ecg_times.append(ecg_times[i]+1000/sample_rate)
сделала

2022-03-25 06:53 UTC, IrinaSozinova commented on lab_1/main.py
> +            else:
исправила

2022-05-11 09:26 UTC, demid5111 requested changes
nice, rework according to the comments

2022-05-11 09:26 UTC, demid5111 commented on lab_2/main.py
> +def calculating_rrd (signal: list):
does type annotation influence any checks?

2022-05-11 09:26 UTC, demid5111 commented on lab_2/main.py
> +    for i in range(0,len(signal [1:])):
creating intermediate copy of a list that takes memory although we do not need it

2022-05-11 09:26 UTC, demid5111 commented on lab_2/main.py
> +        rrd_i=signal[i]-signal[i+1]
when working in PyCharm use formatting of code `Ctrl+Alt+L`

2022-05-11 09:26 UTC, demid5111 commented on lab_2/main.py
> +    for i in range(0,len(signal [1:])):
if starting boundary is 0, it can be omitted, so that **range(N) - 0...N-1**

2022-05-11 09:26 UTC, demid5111 commented on lab_2/main.py
> +    if type(signal) != list:
move all common checks to re-usable function

2022-05-11 09:26 UTC, demid5111 commented on lab_2/main.py
> +    rrd = calculating_rrd(signal)
calculate

2022-05-11 09:26 UTC, demid5111 commented on lab_2/main.py
> +        skobki = i**2
I did not see that

2022-05-11 09:26 UTC, demid5111 commented on lab_2/main.py
> +        sum+=skobki
overriding built-in scope.

2022-05-11 09:26 UTC, demid5111 commented on lab_2/main.py
> +    return round((brackets_sum/(len(rrd[1:])))**0.5, 2)
..

2022-05-11 09:26 UTC, demid5111 commented on lab_2/main.py
> +    return result
if we return several values with a comma, what will be the type? Is it a list??

```suggestion
    return len(nn), round(len(nn)/len(rrd_list), 2)
```

2022-05-11 09:26 UTC, demid5111 commented on lab_2/main.py
> +            f.write(f'{key}\t{value}\n')
extra line?

2022-05-11 09:26 UTC, demid5111 commented on lab_2/main.py
> +        for key, value in hrv_characteristics.items():
replace with single write operation - creating a superstring first?

2022-05-11 09:26 UTC, demid5111 commented on lab_2/main.py
> +    for i in rrd_list:
using comprehensions instead?

2023-09-13 07:51 UTC, closed without merging