Laboratory work #1, Julia Lisivskaia
fss-python/2022-basic-labs pull request #6
Opened 2022-02-22 13:29 UTC by JuliaLisovskaia

2022-02-22 13:32 UTC, demid5111 commented on main.py
> +print('Арифметические операции')
never use russian language in Python scripts

2022-02-22 13:33 UTC, JuliaLisovskaia commented on main.py
> +print('Арифметические операции')
Этот комментарий я считаю избыточным

2022-05-11 09:57 UTC, demid5111 requested changes

2022-05-11 09:57 UTC, demid5111 commented on main.py
> +signal=[8.4,3.3,4.5,1.2,5.6,8.1,4.0,2.3,4.1]
remove from git

2022-05-11 09:57 UTC, demid5111 commented on lab_2/main.py
> +
### Merging changes via merge commit

`git fetch --all`

`git merge origin/main`

Conflicts to be resolved

### Merging changes via rebase (default)

`git pull --rebase`

`git rebase --abort` - to stop rebasing

2022-05-11 09:57 UTC, demid5111 commented on lab_2/main.py
> +    # signal_check(signal)
rework to accept common checks

2022-05-11 09:57 UTC, demid5111 commented on lab_2/main.py
> +    rr_sum = 0
use built-in function for calculating sum of objects in a list

2022-05-11 09:57 UTC, demid5111 commented on lab_2/main.py
> +        if i < len(signal) - 1:
condition should be implicitly included in the range that is used for the loop

2022-05-11 09:57 UTC, demid5111 commented on lab_2/main.py
> +    sdnn = round(sdnn_raw, 2)
intermediate variables

2022-05-11 09:57 UTC, demid5111 commented on lab_2/main.py
> +    rrd_sum = 0
create a separate function for extraction of differences

2022-05-11 09:57 UTC, demid5111 commented on lab_2/main.py
> +            if abs(signal[i] - signal[i + 1]) <= threshold:
reuse rrd calculation

2022-05-11 09:57 UTC, demid5111 commented on lab_2/main.py
> +        for key, value in hrv_characteristics.items():
single write operation is required

2022-05-11 09:57 UTC, demid5111 commented on lab_2/main.py
> +            file.write(f'{key}\t{value}\n')
no new line at the end of the file

2023-09-13 07:51 UTC, closed without merging